### ISSUE TITLE
default values for the qualities

### ISSUE THREAD

**Issue by WAvdBeek** [mjkoster/ODM-Examples#10]
to reduce the qualifiers in each model we should define a default value for each qualifier.
this can be done on schema level.

**Comment by mjkoster** [comment]
Yes, the optionality and default values are not yet specified. I guess we can start making PRs to define these

**Comment by akeranen** [comment]
Some ideas:
* If "name" is omitted, the JSON key name could be used
* default for "optional": true
* default for "observable": true

**Comment by WAvdBeek** [comment]
see nr # in language repo

**Comment by WAvdBeek** [comment]
number 6
