### ISSUE TITLE
type definition

### ISSUE THREAD

**Issue by WAvdBeek** [mjkoster/ODM-Examples#11]
are we following the json definition for types?
e.g. valid values for a type (as enum in the overal schema) : integer, number, string, boolean, array, object
and have a odm:subtype like int64, int32, uint64, uint32, byte (unit8)?

**Comment by mjkoster** [comment]
I have some examples using minimum, maximum, and width to constrain the parameters in the Zigbee definition. subtype using some well known C language types is certainly something we can also do if we feel strongly about it

**Comment by WAvdBeek** [comment]
having a subtype with "C" type like definitions means that we can reuse the existing JSON type mechanism.

e.g.
https://cswr.github.io/JsonSchema/spec/basic_types/

**Comment by WAvdBeek** [comment]
moved to language repo
