### ISSUE TITLE
Namespace Definitions Should Include a Numeric Identifier

### ISSUE THREAD

**Issue by gerickson** [mjkoster/ODM-Examples#2]
We also need a provision for numbered namespace tags. We would advocate for 16-bit vendor namespace identifiers with 0x0000 reserved for ODM and everything else being some vendor (e.g., 0x235A: Nest, 0xE100: Google, etc.).

In Weave, for example, namespace identifiers are used pervasively throughout the protocol binding.

**Comment by mrjerryjohns** [comment]
To be very specific, the top-level element in any full-qualified namespace should be the vendor/organization. This can either be a long-form domain name, or a short-hand name. This element requires a numerical representation, as what Grant has described here.

**Comment by mjkoster** [comment]
I'm not sure we have the same idea of what a namespace is. More discussion is needed.

The current idea in SDF is that a namespace is identified by a URI. The short names are defined in the "namespace" map, and are used as compact URI elements, or CURIEs to resolve prefixes in the identifiers.

The current examples use the short name defined in "defaultnamespace"  as a default prefix, so you don't see any prefixes in the identifiers in the examples.

A namespace isn't only associated with a vendor, and a definition may include terms from multiple namespaces, for example the automotive definitions or HVAC definitions.

What is meant by "full-qualified namespace"? Isn't it a URI? What is meant by "top-level element"? Do you want a number code that represents a vendor in ODM? Is it associated with a URI? What about other semantic namespaces?

**Comment by gerickson** [comment]
> I'm not sure we have the same idea of what a namespace is. More discussion is needed.

Agreed. 

> The current idea in SDF is that a namespace is identified by a URI. The short names are defined in the "namespace" map, and are used as compact URI elements, or CURIEs to resolve prefixes in the identifiers.

I have to confess to being a bit lost here. Were I to do a protocol binding of the ODM DSL as I'm reading it where I need an explicit 16-bit value to indicate a vendor ID in the actual over-the-wire encoding, how would my tooling do that in an offline fashion?

> The current examples use the short name defined in "defaultnamespace" as a default prefix, so you don't see any prefixes in the identifiers in the examples.

I think I comprehend this much. "defaultnamespace" allows me the short hand of "foo.bar" rather than the longhand of "st:foo.st:bar" when the "defaultnamespace" is "st", correct?

> A namespace isn't only associated with a vendor, and a definition may include terms from multiple namespaces, for example the automotive definitions or HVAC definitions.

I'm not clear what the context of "automotive definitions" or "HVAC definitions" are in this case. At some point, there must be a declared vendor ownership of those definitions, correct? Are they "Common" (everyone agreed on them) or are they, for example, the "Ford" or "Society of Automotive Experts (SAE)" vendor for automotive definitions or "Carrier" or "ASHRAE" vendor for the HVAC definitions?

>Do you want a number code that represents a vendor in ODM?

Yes, this is a must.

> What is meant by "full-qualified namespace"? Isn't it a URI? What is meant by "top-level element"?  Is it associated with a URI? What about other semantic namespaces?

I'll let @mrjerryjohns  field those; though, what do you mean by "semantic namespaces"?

**Comment by WAvdBeek** [comment]
not even sure about namespaces.
if we have a list of approved data models then it is just informative of the origin of the approved model.

if we want to keep exact the same syntax, e.g. the numbering of the models as defined by the origin supplier of the model, then we need an extra field to make sure that the approved list has unique numbers. e.g. not using the same number from different supplying orgs.

**Comment by mjkoster** [comment]
namespaceID as a new quality or infoblock parameter
map of URI prefixes to ID? ODM registry for organizationID
Ari will provide some information on IANA registry

**Comment by akeranen** [comment]
One option for numeric IDs is the Private Enterprise Numbers IANA registry:
https://www.iana.org/assignments/enterprise-numbers/enterprise-numbers

That is used e.g., by the [dev-urn](https://tools.ietf.org/html/draft-ietf-core-dev-urn-03) draft already.

**Comment by gerickson** [comment]
Migrated to https://github.com/one-data-model/language/issues/30; closing.
